---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/documents":
    post:
      summary: Upload SVG and generate PDF
      parameters: []
      responses:
        '201':
          description: document created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  pdf_url:
                    type: string
                    format: uri
                required:
                - id
                - name
                - pdf_url
        '400':
          description: bad request
        '415':
          description: unsupported media type
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: file
        description: SVG file to upload
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
